services:
  comfyui:
    image: custom-comfyui:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py --listen 0.0.0.0 --port 8188"]
    ports:
      - 8188:8188
      - 5678:5678
    volumes:
      # Mount models directory
      - ./models/checkpoints:/app/ComfyUI/models/checkpoints
      - ./models:/app/ComfyUI/models
      # Mount input/output directories
      - ./input:/app/ComfyUI/input
      - ./output:/app/ComfyUI/output
      # Mount workflows
      - ./workflows:/app/ComfyUI/user/default/workflows
      # Mount custom nodes
      - ./custom_nodes:/app/ComfyUI/custom_nodes
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
