services:
  comfyui:
    image: custom-comfyui:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8188:8188"
    volumes:
      # Mount entire ComfyUI directory for complete persistence
      - ./comfyui_data:/app/ComfyUI
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
