services:
  comfyui:
    image: custom-comfyui:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' > /tmp/jupyter.log 2>&1 & pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py --listen 0.0.0.0 --port 8188"]
    ports:
      - 8188:8188
      - 8888:8888
      - 5678:5678
    volumes:
      # Bind mount for live code editing and debugging
      # Create a 'comfyui-data' directory in your project to use this
      - ./comfyui-data:/app/ComfyUI
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

# No named volumes needed for debug mode - using bind mount instead
